spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base-admin
    username: root
    password: 551200
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

